name: CI for F# Project

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Build
        run: For /R %%I in (*.sln) do dotnet build %%I

      - name: Run tests
        run: For /R %%I in (*.sln) do dotnet test %%I

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.x

      - name: Build
        run: for f in $(find . -name "*.sln"); do dotnet build $f; done
      - name: Run tests
        run: for f in $(find . -name "*.sln"); do dotnet test $f; done